### ISSUE TITLE
테스트코드 작성

### ISSUE THREAD

**Issue by MinjuKwak01** [Step3-kakao-tech-campus/Team17_BE#40]
## Issue: FEATURE

- [ ] 서비스 계층 테스트코드 작성
- [ ] login()
- [ ] refresh()
- [x] loadDog()
- [ ] writeNotification()
- [ ] editNotification()
- [ ] loadNotification()

## Description

- 각 서비스 계층의 메소드별 테스트코드를 작성합니다.

## ETC

- 기타

**Comment by DEVdongbaek** [comment]
멋있습니다!!

**Comment by DEVdongbaek** [comment]
같이 커버리지 쭉쭉 채워봐요!!
